##spring.application.name=FrogCrew_Back-End
spring:
  datasource:
    url: jdbc:h2:mem:frogcrew
    username: sa
    password:
    driver-class-name: org.h2.Driver
  api:
    endpoint:
      base-url: /api/v1
  jpa:
    show-sql: true



